cabal-version:       2.2

name:                cerviQ
version:             0.1.0.0
synopsis:            Multi-agent grid game with heuristic and Q-learning agents
license:             BSD-3-Clause
license-file:        LICENSE
author:              Matyáš Martinek
copyright:           2026 Matyáš Martinek
category:            Game
build-type:          Simple

extra-source-files:  README.md
                     docs/user-documentation.md
                     docs/developer-documentation.md
                     docs/experiments.md
                     docs/images/.gitkeep


common cerviq-options
  default-language:    Haskell2010

  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints
                       -Wno-missing-export-lists
                       -threaded
                       -O2


library
  import:              cerviq-options

  hs-source-dirs:      src

  exposed-modules:
      Agent
      AgentRegistry
      App
      Collision
      Config
      Controller
      Evaluation
      Game
      Gui
      Maps
      Movement
      PlayGui
      Scenario
      Scenarios
      Training
      TrainingEnvironment
      Types
      Viewport
      QLearning.Core
      QLearning.Debug
      QLearning.V1
      QLearning.V2
      QLearning.V3
      QLearning.V4

  build-depends:
      base >= 4.7 && < 5,
      containers,
      random,
      gloss,
      time ^>=1.12.2


executable cerviQ
  import:              cerviq-options

  hs-source-dirs:      app
  main-is:             Main.hs

  build-depends:
      base >= 4.7 && < 5,
      cerviQ


executable cerviq-train-v4
  import:              cerviq-options

  hs-source-dirs:      app
  main-is:             TrainV4.hs

  build-depends:
      base >= 4.7 && < 5,
      cerviQ


executable cerviq-train
  import:              cerviq-options

  hs-source-dirs:      app
  main-is:             TrainModel.hs

  build-depends:
      base >= 4.7 && < 5,
      cerviQ,
      time ^>=1.12.2


executable cerviq-evaluate
  import:              cerviq-options

  hs-source-dirs:      app
  main-is:             EvaluateModels.hs

  build-depends:
      base >= 4.7 && < 5,
      cerviQ


test-suite cerviq-tests
  import:              cerviq-options

  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs

  build-depends:
      base >= 4.7 && < 5,
      cerviQ,
      tasty,
      tasty-hunit


source-repository head
  type:     git
  location: https://github.com/Maty228/CerviQ
